#!/bin/bash
set -e

echo -e "Duffle Log: Log into Azure"
az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID > /dev/null

if az storage account show -n "${TF_BACKEND_NAME}" -g "${TF_BACKEND_RG}" &> /dev/null; then

    echo -e "Duffle Log: Backend storage account found"
    echo -e "Duffle Log: Checking for backend blob container"

    if az storage container show --name ${CNAB_INSTALLATION_NAME} --account-name "${TF_BACKEND_NAME}" &> /dev/null; then
        echo -e "Duffle Log: Backend blob container found"
        echo -e "Duffle Log: Creating Terraform backend configuration"
    else
        echo -e "Duffle Log: Creating blob for Terraform backend "
        STORAGE_KEY=$(az storage account keys list --account-name $TF_BACKEND_NAME --query [0].value -o tsv)
        az storage container create --name $CNAB_INSTALLATION_NAME --account-name $TF_BACKEND_NAME --account-key $STORAGE_KEY > /dev/null
    fi

else
    echo -e "Duffle Log: Terraform backend storage account not found."

    echo -e "Duffle Log: Creating resource group for Terraform backend"
    az group create --name $TF_BACKEND_RG --location $TF_BACKEND_RG_LOCATION > /dev/null

    echo -e "Duffle Log: Creating storage account for Terraform backend"
    az storage account create --resource-group $TF_BACKEND_RG --name $TF_BACKEND_NAME --sku Standard_LRS --encryption-services blob > /dev/null

    echo -e "Duffle Log: Getting storage account key for Terraform backend"
    ACCOUNT_KEY=$(az storage account keys list --resource-group $TF_BACKEND_RG --account-name $TF_BACKEND_NAME --query [0].value -o tsv)

    echo -e "Duffle Log: Creating storage blob for Terraform backend"
    az storage container create --name $CNAB_INSTALLATION_NAME --account-name $TF_BACKEND_NAME --account-key $ACCOUNT_KEY > /dev/null
fi